### PR TITLE
Fix missing fetch require

### PR DESCRIPTION
**Pull request by marekweb**
This fixes the missing require for `fetch`. Seems that this was related to #29.

### CODE REVIEW

**Comment by remy** [comment]
Would love to see this merged…

**Comment by aaronmarkle** [comment]
Same

**Comment by py4object** [comment]
Please merge this.

**Comment by N0ps32** [comment]
This project is an embarrassment for a company like Shopify. To publish a project like this to npm, officially list it in their API documentation and then show this level of support to the community is a joke.

If Shopify doesn't want to properly support the nodeJS community then they shouldn't publish something like this in the first place and stick to ruby.

The PR has been literally open for a month now and still nobody from Shopify has bothered to update this project. ...aside from all the other issues with this repository that aren't being addressed at all.

**Pull request merged**
